### ISSUE TITLE
exception for triage

### ISSUE THREAD

**Issue by rakslice** [rakslice/twitch-notifier#12]
```
Traceback (most recent call last):
  File "C:\Users\Andrew Tonner\Documents\twitch-notifier\notifiergui\notifier_gui_main.py", line 207, in internal_callback
    callback()
  File "C:\Users\Andrew Tonner\Documents\twitch-notifier\notifiergui\notifier_gui_main.py", line 55, in set_next_time
    time_s, wait_reason = self.main_loop_iter.next()
  File "C:\Users\Andrew Tonner\Documents\twitch-notifier\twitch_notifier_main.py", line 272, in main_loop_yielder
    self.done_state_changes()
  File "C:\Users\Andrew Tonner\Documents\twitch-notifier\notifiergui\notifier_gui_main.py", line 126, in done_state_changes
    for channel_id in self.previously_online_streams:
RuntimeError: Set changed size during iteration
```

**Comment by rakslice** [comment]
set remove during iter
